// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'FPaineisRGraficoLinha.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FPaineisRGraficoLinha _$FPaineisRGraficoLinhaFromJson(
        Map<String, dynamic> json) =>
    FPaineisRGraficoLinha(
      listaPontos: (json['listaPontos'] as List<dynamic>?)
          ?.map((e) => (e as num).toInt())
          .toList(),
      iTipoLinha: (json['iTipoLinha'] as num?)?.toInt() ?? 1,
      sTituloNome: json['sTituloNome'] as String? ?? "Grafico de Linha",
      oTituloCor: (json['oTituloCor'] as num?)?.toInt() ?? 0xFF000000,
      iTituloExibir: (json['iTituloExibir'] as num?)?.toInt() ?? 1,
      iTituloCimaBaixo: (json['iTituloCimaBaixo'] as num?)?.toInt() ?? 1,
      iMostrarBorda: (json['iMostrarBorda'] as num?)?.toInt() ?? 2,
      corDaBorda: (json['corDaBorda'] as num?)?.toInt() ?? 0xFF000000,
      iMostarGrid: (json['iMostarGrid'] as num?)?.toInt() ?? 1,
      iPontosArredondados: (json['iPontosArredondados'] as num?)?.toInt() ?? 1,
      iPontasArredondadas: (json['iPontasArredondadas'] as num?)?.toInt() ?? 1,
      iMostrarPontos: (json['iMostrarPontos'] as num?)?.toInt() ?? 2,
      iPreencherArea: (json['iPreencherArea'] as num?)?.toInt() ?? 2,
      iEixoXAltura: (json['iEixoXAltura'] as num?)?.toInt() ?? 30,
      oEixoXCor: (json['oEixoXCor'] as num?)?.toInt() ?? 0xFF000000,
      iEixoXExibir: (json['iEixoXExibir'] as num?)?.toInt() ?? 2,
      iEixoXCimaBaixo: (json['iEixoXCimaBaixo'] as num?)?.toInt() ?? 1,
      iEixoXExibirTitulo: (json['iEixoXExibirTitulo'] as num?)?.toInt() ?? 2,
      iEixoYAltura: (json['iEixoYAltura'] as num?)?.toInt() ?? 30,
      oEixoYCor: (json['oEixoYCor'] as num?)?.toInt() ?? 0xFF000000,
      iEixoYExibir: (json['iEixoYExibir'] as num?)?.toInt() ?? 2,
      iEixoYEsquerdaDireita:
          (json['iEixoYEsquerdaDireita'] as num?)?.toInt() ?? 1,
      iEixoYExibirTitulo: (json['iEixoYExibirTitulo'] as num?)?.toInt() ?? 2,
      dLinha1Espessura: (json['dLinha1Espessura'] as num?)?.toDouble() ?? 5,
      oLinha1Cor: (json['oLinha1Cor'] as num?)?.toInt() ?? 0xFFFF0000,
      oLinha1AreaCor: (json['oLinha1AreaCor'] as num?)?.toInt(),
      iLinha1CorGradiente: (json['iLinha1CorGradiente'] as num?)?.toInt(),
      iLinha1AreaGradiente: (json['iLinha1AreaGradiente'] as num?)?.toInt(),
      iLinha1Tipo: (json['iLinha1Tipo'] as num?)?.toInt() ?? 1,
      iLinha1AreaCimaBaixo:
          (json['iLinha1AreaCimaBaixo'] as num?)?.toInt() ?? 2,
      iLinha1Sombra: (json['iLinha1Sombra'] as num?)?.toInt() ?? 2,
      oLinha1SombraCor: (json['oLinha1SombraCor'] as num?)?.toInt(),
      dLinha2Espessura: (json['dLinha2Espessura'] as num?)?.toDouble(),
      oLinha2Cor: (json['oLinha2Cor'] as num?)?.toInt(),
      oLinha2AreaCor: (json['oLinha2AreaCor'] as num?)?.toInt(),
      iLinha2CorGradiente: (json['iLinha2CorGradiente'] as num?)?.toInt(),
      iLinha2AreaGradiente: (json['iLinha2AreaGradiente'] as num?)?.toInt(),
      iLinha2Tipo: (json['iLinha2Tipo'] as num?)?.toInt(),
      iLinha2AreaCimaBaixo: (json['iLinha2AreaCimaBaixo'] as num?)?.toInt(),
      iLinha2Sombra: (json['iLinha2Sombra'] as num?)?.toInt(),
      oLinha2SombraCor: (json['oLinha2SombraCor'] as num?)?.toInt(),
      dLinha3Espessura: (json['dLinha3Espessura'] as num?)?.toDouble(),
      oLinha3Cor: (json['oLinha3Cor'] as num?)?.toInt(),
      oLinha3AreaCor: (json['oLinha3AreaCor'] as num?)?.toInt(),
      iLinha3CorGradiente: (json['iLinha3CorGradiente'] as num?)?.toInt(),
      iLinha3AreaGradiente: (json['iLinha3AreaGradiente'] as num?)?.toInt(),
      iLinha3Tipo: (json['iLinha3Tipo'] as num?)?.toInt(),
      iLinha3AreaCimaBaixo: (json['iLinha3AreaCimaBaixo'] as num?)?.toInt(),
      iLinha3Sombra: (json['iLinha3Sombra'] as num?)?.toInt(),
      oLinha3SombraCor: (json['oLinha3SombraCor'] as num?)?.toInt(),
      dLinha4Espessura: (json['dLinha4Espessura'] as num?)?.toDouble(),
      oLinha4Cor: (json['oLinha4Cor'] as num?)?.toInt(),
      oLinha4AreaCor: (json['oLinha4AreaCor'] as num?)?.toInt(),
      iLinha4CorGradiente: (json['iLinha4CorGradiente'] as num?)?.toInt(),
      iLinha4AreaGradiente: (json['iLinha4AreaGradiente'] as num?)?.toInt(),
      iLinha4Tipo: (json['iLinha4Tipo'] as num?)?.toInt(),
      iLinha4AreaCimaBaixo: (json['iLinha4AreaCimaBaixo'] as num?)?.toInt(),
      iLinha4Sombra: (json['iLinha4Sombra'] as num?)?.toInt(),
      oLinha4SombraCor: (json['oLinha4SombraCor'] as num?)?.toInt(),
    );

Map<String, dynamic> _$FPaineisRGraficoLinhaToJson(
        FPaineisRGraficoLinha instance) =>
    <String, dynamic>{
      'listaPontos': instance.listaPontos,
      'iTipoLinha': instance.iTipoLinha,
      'sTituloNome': instance.sTituloNome,
      'oTituloCor': instance.oTituloCor,
      'iTituloExibir': instance.iTituloExibir,
      'iTituloCimaBaixo': instance.iTituloCimaBaixo,
      'iMostrarBorda': instance.iMostrarBorda,
      'corDaBorda': instance.corDaBorda,
      'iMostarGrid': instance.iMostarGrid,
      'iPontosArredondados': instance.iPontosArredondados,
      'iPontasArredondadas': instance.iPontasArredondadas,
      'iMostrarPontos': instance.iMostrarPontos,
      'iPreencherArea': instance.iPreencherArea,
      'iEixoXAltura': instance.iEixoXAltura,
      'oEixoXCor': instance.oEixoXCor,
      'iEixoXExibir': instance.iEixoXExibir,
      'iEixoXCimaBaixo': instance.iEixoXCimaBaixo,
      'iEixoXExibirTitulo': instance.iEixoXExibirTitulo,
      'iEixoYAltura': instance.iEixoYAltura,
      'oEixoYCor': instance.oEixoYCor,
      'iEixoYExibir': instance.iEixoYExibir,
      'iEixoYEsquerdaDireita': instance.iEixoYEsquerdaDireita,
      'iEixoYExibirTitulo': instance.iEixoYExibirTitulo,
      'dLinha1Espessura': instance.dLinha1Espessura,
      'oLinha1Cor': instance.oLinha1Cor,
      'oLinha1AreaCor': instance.oLinha1AreaCor,
      'iLinha1CorGradiente': instance.iLinha1CorGradiente,
      'iLinha1AreaGradiente': instance.iLinha1AreaGradiente,
      'iLinha1Tipo': instance.iLinha1Tipo,
      'iLinha1AreaCimaBaixo': instance.iLinha1AreaCimaBaixo,
      'iLinha1Sombra': instance.iLinha1Sombra,
      'oLinha1SombraCor': instance.oLinha1SombraCor,
      'dLinha2Espessura': instance.dLinha2Espessura,
      'oLinha2Cor': instance.oLinha2Cor,
      'oLinha2AreaCor': instance.oLinha2AreaCor,
      'iLinha2CorGradiente': instance.iLinha2CorGradiente,
      'iLinha2AreaGradiente': instance.iLinha2AreaGradiente,
      'iLinha2Tipo': instance.iLinha2Tipo,
      'iLinha2AreaCimaBaixo': instance.iLinha2AreaCimaBaixo,
      'iLinha2Sombra': instance.iLinha2Sombra,
      'oLinha2SombraCor': instance.oLinha2SombraCor,
      'dLinha3Espessura': instance.dLinha3Espessura,
      'oLinha3Cor': instance.oLinha3Cor,
      'oLinha3AreaCor': instance.oLinha3AreaCor,
      'iLinha3CorGradiente': instance.iLinha3CorGradiente,
      'iLinha3AreaGradiente': instance.iLinha3AreaGradiente,
      'iLinha3Tipo': instance.iLinha3Tipo,
      'iLinha3AreaCimaBaixo': instance.iLinha3AreaCimaBaixo,
      'iLinha3Sombra': instance.iLinha3Sombra,
      'oLinha3SombraCor': instance.oLinha3SombraCor,
      'dLinha4Espessura': instance.dLinha4Espessura,
      'oLinha4Cor': instance.oLinha4Cor,
      'oLinha4AreaCor': instance.oLinha4AreaCor,
      'iLinha4CorGradiente': instance.iLinha4CorGradiente,
      'iLinha4AreaGradiente': instance.iLinha4AreaGradiente,
      'iLinha4Tipo': instance.iLinha4Tipo,
      'iLinha4AreaCimaBaixo': instance.iLinha4AreaCimaBaixo,
      'iLinha4Sombra': instance.iLinha4Sombra,
      'oLinha4SombraCor': instance.oLinha4SombraCor,
    };
